#
# This playbook does an end to end run of the magpie module and action_plugin.  If this playbook
# is in the top level of this source tree it will use the magpie module from 'library' and
# action_plugin from 'action_plugins'.
#
# Run the 'ansible-playbook' command below after setting HOSTLIST and REDHAT_PORTAL_CREDS_FILE.
#
# This test requires a test host.  This must be a RHEL box (real or virtual) that
# is both registered with Red Hat Insights, and in your Ansible inventory (and reachable by ansible)
# on your development machine.  If you want to test multiple hosts, separate
# hostnames with commas.
#
# This test requires Red Hat Insights basic auth credentials to be supplied in
# a YAML file.  I put this file outside the source repo so i don't accedently push it.
#
#    redhat_portal_username: XXXXXX
#    redhat_portal_password: YYYYYY
#
# where XXXX and YYYYY are replaced with Red Hat Portal basic auth credentials.
# 
# HOSTLIST=host1.example.com,host2.example.com
#    a comma separated list of hosts in your Ansible inventory
# REDHAT_PORTAL_CREDS_FILE=redhat-portal-creds.yml
#    a file containing your Red Hat Portal BASIC AUTH creds
#
# ansible-playbook --limit "$HOSTLIST" --extra-vars @${REDHAT_PORTAL_CREDS_FILE} local_module_test.yml
#
- hosts: all
  tasks:
     - magpie:
     - debug: msg="{{ insights_upload_results.reports }}"
