#
# HOSTLIST=host1.example.com,host2.example.com
#    a comma separated list of hosts in your Ansible inventory
# REDHAT_PORTAL_CREDS_FILE=redhat-portal-creds.yml
#    a file containing your Red Hat Portal BASIC AUTH creds
#
# ansible-playbook --limit "$HOSTLIST" --extra-vars @${REDHAT_PORTAL_CREDS_FILE} test.yml
#
- hosts: all
  tasks:
     - magpie:
     - debug: msg="{{ insights_upload_results.reports }}"
